name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: write
    uses: ./.github/workflows/template-release-docs.yml
    with:
      name: "BlazorFocused.Testing Documentation"
      documentation-folder-path: docs
      github-pages-branch: gh-pages
      github-user-email: blazorfocused-automation@users.noreply.github.com
      github-user-name: Pages-Automation
